accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from devsearch import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='projects/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import include, path
from . import views

app_name = "profiles"

skill_urlpatterns = [
    path("create/", views.create_skill, name="create-skill"),
    path("edit/<uuid:pk>", views.edit_skill, name="edit-skill"),
    path("delete/<uuid:pk>", views.delete_skill, name="delete-skill"),
]

personal_urlpatterns = [
    path('', views.personal_profile, name='personal'),
    path('skills/', include(skill_urlpatterns)),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<uuid:pk>', views.message, name='message'),
    path('inbox/create/', views.create_message, name='create-message'),
]

urlpatterns = [
    path('', views.profiles, name='list'),
    path('<uuid:pk>/', views.profile, name='get'),
    path('personal/', include(personal_urlpatterns)),
    
]

projects/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings
app_name = "projects"
urlpatterns = [
    path('', views.projects, name='list'),
    path('<uuid:pk>', views.project, name='get'),
    path('create/', views.create_project, name='create'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit'),
    path('<uuid:pk>/delete/', views.delete_project, name='delete'),
]

profiles/models.py
import uuid

from django.db import models

from django.contrib.auth.models import User

from profiles.validators import ValidateMinLength



# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=150, blank=True, null=True)
    location = models.CharField(max_length=150, blank=True, null=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    short_intro = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True, default="profile_images/user-default.png", upload_to="profile_images/")
    social_github = models.CharField(max_length=100, blank=True, null=True)
    social_twitter = models.CharField(max_length=100, blank=True, null=True)
    social_youtube = models.CharField(max_length=100, blank=True, null=True)
    social_linkedin = models.CharField(max_length=100, blank=True, null=True)
    social_stackoverflow = models.CharField(max_length=100, blank=True, null=True)
    social_website = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)
    
class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500, validators=[ValidateMinLength(200)])
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='sent_messages')
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='messages')
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=150)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ['is_read', '-created']
        constraints = [
            models.CheckConstraint(check=~models.Q(sender=models.F('recipient')), name='sender_not_recipient')
        ]

profiles/forms.py
from django.forms import HiddenInput, ModelForm
from django import forms
from .models import Skill, Message

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ('name', 'description')
        widgets = {
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'})
        }
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for k, v in self.fields.items():
            v.widget.attrs.update({'class':'input', 'placeholder': f'Add {k}'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ('recipient', 'sender', 'name', 'email', 'subject', 'body')
    
    def __init__(self, *args, **kwargs):
        self.sender = kwargs.pop('sender', None)
        self.recipient = kwargs.pop('recipient', None)
        self.name = self.sender.name if self.sender else None
        self.email = self.sender.email if self.sender else None
        super(MessageForm, self).__init__(*args, **kwargs)
        
        self.fields['recipient'] = forms.ModelChoiceField(queryset=self.fields['recipient'].queryset.exclude(id=self.sender.id) if self.sender else self.fields['recipient'].queryset)
        self.fields['recipient'].initial = self.recipient
        
        if self.sender:
            self.fields['sender'].widget = HiddenInput()
            self.fields['name'].widget = HiddenInput()
            self.fields['email'].widget = HiddenInput()
            self.fields['sender'].initial = self.sender
            self.fields['name' ].initial = self.sender.name
            self.fields['email'].initial = self.sender.email

        for k, v in self.fields.items():
            v.widget.attrs.update({'class':'input'})

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()

        if cleaned_data['sender'].id == cleaned_data['recipient'].id:
            raise forms.ValidationError('Você não pode enviar uma mensagem para você mesmo.')
        return cleaned_data

profiles/views.py
from django.shortcuts import redirect, render

from django.contrib import messages

from django.db.models import Q

from django.contrib.auth.decorators import login_required

from profiles.forms import MessageForm, SkillForm

from .models import Profile
from projects.models import Project

def profiles(request):
    search_query = request.GET.get('search_query', '')
    profiles = Profile.objects.filter(
        Q(name__icontains=search_query) | 
        Q(bio__icontains=search_query)  |
        Q(short_intro__icontains=search_query) |
        Q(skill__name__icontains=search_query)
    ).distinct()
    context = {'profiles': profiles, 'search_query': search_query}
    return render(request, 'profiles/list.html', context)

def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    projects = Project.objects.filter(owner=pk)
    context = {'profile': profile, 'projects': projects}
    return render(request, 'profiles/detail.html', context)


@login_required(login_url="accounts:login")
def inbox(request):
    profile = request.user.profile
    messages = profile.messages.all()
    unread_messages_length = profile.messages.filter(is_read=False).count()
    context = {'profile': profile, 'inbox_messages': messages, 'unread_messages_length': unread_messages_length}
    return render(request, 'profiles/inbox.html', context)

@login_required(login_url="accounts:login")
def message(request, pk):
    profile = request.user.profile
    message = profile.messages.get(pk=pk)
    message.is_read = True
    message.save()
    context = {'message': message}
    return render(request, 'profiles/message.html', context)

def create_message(request):
    recipient_id = request.GET.get('recipient', '')
    recipient = Profile.objects.get(pk=recipient_id) if recipient_id else None
    sender = request.user.profile if request.user.is_authenticated else None
    form = MessageForm(recipient=recipient, sender=sender)

    if request.method == 'POST':
        form = MessageForm(request.POST, sender=sender, recipient=recipient)
        if form.is_valid():
            form.save()
            messages.success(request, 'Mensagem enviada com sucesso!')
            return redirect('profiles:get', pk=recipient.id if recipient else sender.id)
        else:
            messages.error(request, 'Erro ao enviar mensagem.')
    
    context = {'form': form, 'recipient': recipient, 'sender': sender}
    return render(request, 'profiles/message-form.html', context)

@login_required(login_url="accounts:login")
def personal_profile(request):
    profile = request.user.profile
    projects = profile.project_set.all()
    context = {'profile': profile, 'projects': projects}
    return render(request, 'profiles/personal-detail.html', context)

@login_required(login_url="accounts:login")
def create_skill(request):

    form = SkillForm()

    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = request.user.profile
            skill.save()
            return redirect('profiles:personal')
    
    context = {'form': form}
    return render(request, 'profiles/skill-form.html', context)

@login_required(login_url="accounts:login")
def edit_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(pk=pk)
    form = SkillForm(instance=skill)

    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            return redirect('profiles:personal')
    
    context = {'form': form}
    return render(request, 'profiles/skill-form.html', context)
    
@login_required(login_url="accounts:login")
def delete_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(pk=pk)

    if request.method == 'POST':
        skill.delete()
        return redirect('profiles:personal')
    
    context = {'object': skill}
    return render(request, 'delete.html', context)

profiles/templates/profiles/detail.html
{% extends 'main.html' %}

{% block content %}
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              {% if profile.location%}<p class="dev__location">{{profile.location}}</p>{% endif %}
              <ul class="dev__social">
                {% if profile.social_github %}
                  <li>
                    <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa-brands fa-github"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_stackoverflow %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="fa-brands fa-stack-overflow"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="fa-brands fa-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa-solid fa-globe"></i></a>
                </li>
                {% endif %}

              </ul>
              <a href="{% url 'profiles:create-message'%}?recipient={{profile.id}}" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {% with total_skills=profile.skill_set.all %}
            
            {% for skill in total_skills|slice:":3" %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
            {% endfor %}
            {% if total_skills|length > 3 %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in profile.skill_set.all|slice:"3:" %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
                {% endfor %}
              </div>
            {% endif %}
            {% endwith %}
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              {% for project in projects %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'projects:get' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="#">{{project.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Posititive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize }})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock content %}

profiles/templates/profiles/inbox.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <div style="display: flex; justify-content: space-between">
      <h3 class="inbox__title">New Messages(<span>{{unread_messages_length}}</span>)</h3>
      <a href="{% url 'profiles:create-message' %}">Enviar mensagem</a>
    </div>
    <ul class="messages">
      {% for m in inbox_messages%}
      <li class="message {% if not m.is_read%}message--unread{% endif %}">
        <a href="{% url 'profiles:message' m.id %}">
          <span class="message__author">{{m.name}}</span>
          <span class="message__subject">{{m.subject}}</span>
          <span class="message__date">{{m.created}}</span>
        </a>
      </li>
      {% empty %}
      <p>You have no messages.</p>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock %}

profiles/templates/profiles/list.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
          <h3>{{search_query}}</h3>
        </div>
        <div class="hero-section__search">
          <form class="form" method="get">
            <div class="form__field">
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                value="{{search_query}}" placeholder="Search by developer" data-testid="search-input"/>
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" data-testid="search-button"/>
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three" data-testid="profiles">
        {% for profile in profiles %}
          <div class="column card">
            <div class="dev" data-testid="profile">
              <a href="{% url 'profiles:get' profile.id%}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{profile.bio}}
                </p>
                <div class="dev__skills" data-testid="tags">
                {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main" data-testid="tag">
                    <small>{{skill.name}}</small>
                  </span>
                {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>

    {% include 'pagination.html' with queryset=profiles%}
  </main>
{% endblock content %}

profiles/templates/profiles/message-form.html
{% extends 'main.html'%}

{% block content %}
<body>
    <!-- Main Section -->
    <main class="formPage my-xl">
        
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" onclick="history.back()" href="#"><i class="fa-solid fa-chevron-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    
                    <div class="form__field">
                        {% if not field.is_hidden %}
                        <label for="formInput#text">{{ field.label }} </label>
                        {% endif %}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>

                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
            </div>
        </div>
    </main>
</body>
{% endblock content %}

profiles/templates/profiles/message.html
{% extends 'main.html' %}

{% block content %}

<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'profiles:inbox'%}" href="#"><i class="fa-solid fa-chevron-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h4>
        <a href="profile.html" class="message__author">{{message.name}}</a>
        <p class="message__date">{{message.created}}/p>
        <div class="message__body">
          {{message.body}}
        </div>
    </div>
  </div>
</main>

{% endblock %}

profiles/templates/profiles/personal-detail.html
{% extends 'main.html' %}

{% block content %}
<body>
    <main class="settingsPage profile my-md">
    <div class="container">
        <div class="layout">
        <div class="column column--1of3">
            <div class="card text-center">
            <div class="card__body dev">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i style="margin-right: .4em;"class="fa-solid fa-pen-to-square"></i> Edit</a>
                <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
                <h2 class="dev__name">{{profile.name}}</h2>
                <p class="dev__title">{{profile.short_intro}}</p>
                {% if profile.location%}<p class="dev__location">{{profile.location}}</p>{% endif %}
                <ul class="dev__social">
                  {% if profile.social_github %}
                    <li>
                      <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa-brands fa-github"></i></a>
                    </li>
                  {% endif %}
                  {% if profile.social_stackoverflow %}
                  <li>
                    <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="fa-brands fa-stack-overflow"></i></a>
                  </li>
                  {% endif %}
                  {% if profile.social_twitter %}
                  <li>
                    <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="fa-brands fa-twitter"></i></a>
                  </li>
                  {% endif %}
                  {% if profile.social_linkedin %}
                  <li>
                    <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                  </li>
                  {% endif %}
                  {% if profile.social_website %}
                  <li>
                    <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa-solid fa-globe"></i></a>
                  </li>
                  {% endif %}
  
                </ul>
            </div>
            </div>
        </div>
        <div class="column column--2of3">
            <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{profile.bio}}
            </p>
            </div>
            <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'profiles:create-skill' %}"><i style="margin-right: .4em"  class="fa-solid fa-plus"></i> Add Skill</a>
            </div>

            <table class="settings__table">
                {% for skill in profile.skill_set.all %}
                <tr>
                    <td class="settings__tableInfo">
                    <h4>{{skill.name}}</h4>
                    <p>
                        {{skill.description}}
                    </p>
                    </td>
                    <td class="settings__tableActions">
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'profiles:edit-skill' skill.id %}"><i style="margin-right: .4em;"class="fa-solid fa-pen-to-square"></i> Edit</a>
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'profiles:delete-skill' skill.id %}?next=/profiles/personal/"><i style="margin-right: .4em" class="fa-solid fa-trash"></i>
                        Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </table>

            <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create' %}"><i style="margin-right: .4em" class="fa-solid fa-plus"></i> Add Project</a>
            </div>

            <table class="settings__table">
                {% for project in projects %}
                <tr>
                    <td class="settings__thumbnail">
                    <a href="{% url 'projects:get' project.id %}">
                        <img src="{{project.featured_image.url}}" alt="project thumbnail" />
                    </a>
                    </td>
                    <td class="settings__tableInfo">
                        <a href="{% url 'projects:get' project.id %}">{{project.title}}</a>
                    <p>
                        {{project.description}}
                    </p>
                    </td>
                    <td class="settings__tableActions">
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:edit' project.id %}"><i style="margin-right: .4em;"class="fa-solid fa-pen-to-square"></i> Edit</a>
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete' project.id %}?next=/profiles/personal/"><i style="margin-right: .4em" class="fa-solid fa-trash"></i>
                        Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        </div>
    </div>
    </main>
</body>
{% endblock content %}

profiles/templates/profiles/skill-form.html
{% extends 'main.html'%}

{% block content %}
<body>
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" onclick="history.back()" href="#"><i class="fa-solid fa-chevron-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }} </label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>

                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
            </div>
        </div>
    </main>
</body>
{% endblock content %}