accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from devsearch import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='projects/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import include, path
from . import views

app_name = "profiles"

skill_urlpatterns = [
    path("create/", views.create_skill, name="create-skill"),
    path("edit/<uuid:pk>", views.edit_skill, name="edit-skill"),
    path("delete/<uuid:pk>", views.delete_skill, name="delete-skill"),
]

personal_urlpatterns = [
    path('', views.personal_profile, name='personal'),
    path('skills/', include(skill_urlpatterns)),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<uuid:pk>', views.message, name='message'),
    path('inbox/create/', views.create_message, name='create-message'),
]

urlpatterns = [
    path('', views.profiles, name='list'),
    path('<uuid:pk>/', views.profile, name='get'),
    path('personal/', include(personal_urlpatterns)),
    
]

projects/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings
app_name = "projects"
urlpatterns = [
    path('', views.projects, name='list'),
    path('<uuid:pk>', views.project, name='get'),
    path('create/', views.create_project, name='create'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit'),
    path('<uuid:pk>/delete/', views.delete_project, name='delete'),
]

projects/models.py
import os
from django.db import models
import uuid

from profiles.models import Profile

# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, blank=True)
    vote_ratio = models.IntegerField(default=0, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="projects/default.jpg", upload_to="projects")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    def image_exists(self):
        if self.featured_image:
            return os.path.isfile(self.featured_image.path)
        return False
    
    @property
    def up_votes(self):
        return self.review_set.filter(value='up').count()
    
    @property
    def total_votes(self):
        return self.review_set.count()
    
    @property
    def ratio(self):
        if self.total_votes > 0:
            ratio = (self.up_votes / self.total_votes) * 100
            return int(ratio)
        return 0
    
    @property
    def reviewers_ids(self):
        reviews = self.review_set.all().values_list('owner__id', flat=True)
        return [id for id in reviews if id is not None]

        
    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=10, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['owner', 'project'], name='unique review by project per user')
        ]
    def __str__(self):
        return self.value
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.project.vote_total = self.project.total_votes
        self.project.vote_ratio = self.project.ratio
        self.project.save()

    

class Tag(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project, Review

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'featured_image', 'source_link', 'demo_link', 'tags')
        widgets = {
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'})
        }
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for k, v in self.fields.items():
            v.widget.attrs.update({'class':'input', 'placeholder': f'Add {k}'})

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('value', 'body', )
        labels = {
            'body': 'Add a comment',
            'value': 'Place your vote'
        }

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner', None)
        self.project = kwargs.pop('project', None)
        super(ReviewForm, self).__init__(*args, **kwargs)
        for v in self.fields.values():
            v.widget.attrs.update({'class':'input'})
        
    def clean(self):
        cleaned_data = super(ReviewForm, self).clean()
        if Review.objects.filter(owner=self.owner, project=self.project).exists():
            raise forms.ValidationError('You have already reviewed this project.')
        if self.owner.id == self.project.owner.id:
            raise forms.ValidationError('You cannot review your own project.')
        return cleaned_data

projects/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
from django.db.models import Q
from projects.forms import ProjectForm, ReviewForm
from projects.utils import get_int_param, get_page_param
from .models import Project

def projects(request):

    search_query = request.GET.get('search_query', '')
    page_len = get_int_param(request, 'page_len', 3)

    projects = Project.objects.filter(
        Q(title__icontains=search_query) | 
        Q(description__icontains=search_query)  |
        Q(owner__name__icontains=search_query)  |
        Q(tags__name__icontains=search_query)
    ).distinct()
    paginator = Paginator(projects, page_len)

    page = get_page_param(request, 'page', 1, paginator.num_pages)
    projects_page = paginator.page(page)
        
    context = {
        'projects': projects_page, 'search_query': search_query, 'paginator': paginator
    }

    return render(request, 'projects/list.html', context)

def project(request, pk):
    project = Project.objects.get(pk=pk)
    review_form = ReviewForm()
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, owner=request.user.profile, project=project)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.project = project
            if request.user.is_authenticated:
                review.owner = request.user.profile
            review.save()
            messages.success(request, 'Review submitted successfully!')
            return redirect('projects:get', pk=pk)
        else:
            messages.error(request, 'There was an error with your submission.')

    context = {
        'project': project, 'review_form': review_form
    }
    return render(request, 'projects/detail.html', context)

@login_required(login_url="accounts:login")
def create_project(request):
    
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user.profile
            project.save()
            return redirect('profiles:personal')
    
    context = {'form': form}
    return render(request, 'projects/form.html', context)

@login_required(login_url="accounts:login")
def edit_project(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(pk=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects:list')
    context = {'form': form}
    return render(request, 'projects/form.html', context)

@login_required(login_url="accounts:login")
def delete_project(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(pk=pk)
    context = {'object': project}
    if request.method == 'POST':
        project.delete()
        return redirect('projects:list')
    return render(request, 'delete.html', context)

projects/templates/projects/detail.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<body>
    <!-- Main Section -->
    <main class="singleProject my-md">
      <div class="container">
        <div class="layout">
          <div class="column column--1of3">
            <h3 class="singleProject__subtitle">Tools & Stacks</h3>
            <div class="singleProject__toolStack">
  
              {% for tag in project.tags.all%}
              <span class="tag tag--pill tag--sub tag--lg">
                <small>{{tag}}</small>
              </span>
              {% endfor %}
            </div>
            {% if project.source_link %}
            <a class="singleProject__liveLink" href="{{project.source_link}}" target="_blank"><i class="im im-external-link"></i>
              Source code
            </a>
            {% endif %}

            {% if project.demo_link %}
            <a class="singleProject__liveLink" href="{{project.demo_link}}" target="_blank"><i class="im im-external-link"></i>
              Live demo
            </a>
            {% endif %}
          </div>
          <div class="column column--2of3">
            <img class="singleProject__preview" src="{% if project.image_exists %} {{project.featured_image.url}} {% else %} /media/projects/default.jpg {% endif %}" alt="portfolio thumbnail" />
            <a href="{% url 'profiles:get' project.owner.id %}" class="singleProject__developer">{{project.owner.name}}</a>
            <h2 class="singleProject__title">{{project.title}}</h2>
            <h3 class="singleProject__subtitle">{{project.description}}</h3>
            <div class="singleProject__info">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima harum maxime debitis amet voluptates esse
              a perferendis tempora, natus pariatur obcaecati odit quisquam fugit deserunt.
  
              <br />
              <br />
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic voluptates earum possimus a perferendis culpa
              omnis, libero quae soluta, obcaecati amet. Quam earum ad qui reprehenderit eligendi porro ab possimus
              fugit voluptatem rerum eius sapiente, nemo mollitia aperiam suscipit culpa corrupti officiis dicta soluta
              ut similique! Iste soluta quae tempora alias assumenda? Nam nesciunt nihil enim tempore cum quo
              architecto?
            </div>
            
            <div class="comments" data-testid="comments">
              {% if project.vote_total > 0 %}
              <h3 class="singleProject__subtitle">Feedback</h3>
              <h5 class="project--rating">
                <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Posititive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize }})
              </h5>
              <div class="commentList" data-testid="comment-list">
                {% for review in project.review_set.all|dictsortreversed:"created" %}
                <div class="comment" data-testid="comment">
                  {% if review.owner %}
                  <a href="{% url 'profiles:get' review.owner.id %}">
                    <img class="avatar avatar--md"
                      src="{{review.owner.profile_image.url}}" alt="user" />
                  </a>
                  {% else %}
                    <img class="avatar avatar--md"
                        src="{% static 'images/user-default.png' %}" alt="user" />
                  {% endif %}
                  <div class="comment__details">
                    {% if review.owner %}
                    <a href="{% url 'profiles:get' review.owner.id %}" class="comment__author">
                      {{review.owner.name}} {% if review.owner.user.id == user.id %} (You) {% endif %}
                    </a>
                    {% else %}
                    <strong>User deleted</strong>
                    {% endif %}
                    <p style="font-size: 1.1em">
                      {{review.body}}
                    </p>
                    <p style="font-size: .9em">{{review.created|date:"d/m/Y à\s H:i:s"}}</p>
                  </div>
                </div>
                {% endfor %}
              </div>
              {% else %}
                <h3 class="singleProject__subtitle">Feedback</h3>
                <h5 class="project--rating">
                  This project don't have review yet.
                </h5>
              {% endif %}
            </div>


            {% if user.profile.id in project.reviewers_ids %}
              <p>You already reviewed this project.</p>
            {% elif user.id == project.owner.user.id %}
              <p>You cannot review your own project.</p>
            {% elif user.is_authenticated %}
              <form class="form" method="POST" data-testid="comment-form">
                {% csrf_token %}
                {% for field in review_form %}
                <!-- Input:Text -->
                <div class="form__field">
                  <label for="formInput#text">{{field.label}} </label>
                    {{ field }}
                </div>
                {% endfor %}
                {% if review_form.non_field_errors %}
                  {% for error in review_form.non_field_errors %}
                    <div class="error-messages">
                      <p style="color: red">{{error}}</p>
                    </div>
                  {% endfor %}
                {% endif %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
              </form>
            {% else %}
              <p>You need to <span><a href="{% url 'accounts:login' %}?next={{request.path}}">Login</a></span> to review a project </p>
              
            {% endif %}
          </div>
        </div>
      </div>
      </div>
    </main>
  </body>
  
  </html>

{% endblock content %}

projects/templates/projects/form.html
{% extends 'main.html' %}
{% block content %}
<body>
    <!-- Main Section -->
    <main class="formPage my-xl">
            
                <a class="backButton" href="#"><i class="fa-solid fa-chevron-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    {% for field in form%}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
    
    </main>
</body>
{% endblock %}

projects/templates/projects/list.html
{% extends 'main.html' %}

{% block content %}
<main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form id="search-form" class="form" action="#" method="get">
            <div class="form__field">
  
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                value="{{search_query}}"
                placeholder="Search by Project" 
                data-testid="search-input"/>
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" data-testid="search-button"//>
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div data-testid="projects" class="grid grid--three">
          {% for project in projects %}
            <div class="column">
              <div class="card project" data-testid="project">
                <a href="{% url 'projects:get' project.id%}" class="project">
                  <img class="project__thumbnail" src="{% if project.image_exists %} {{project.featured_image.url}} {% else %} /media/projects/default.jpg {% endif %}" alt="project thumbnail" />
                  <div class="card__body">
                    <h3 class="project__title">{{ project.title }}</h3>
                    <p><a class="project__author" href="{% url 'profiles:get' project.owner.id %}">{% if project.owner %}By {{project.owner.name}}{% else %}{% endif %}</a></p>
                    
                    <p class="project--rating">
                      <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Posititive
                              Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize }})
                    </p>
                    
                    <div class="project__tags" data-testid="tags">
                      {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main" data-testid="tag">
                        <small>{{tag.name}}</small>
                      </span>
                      {% endfor %}
                      
                    </div>
                  </div>
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>

  {% include 'pagination.html' with queryset=projects%}
</main>

{% endblock content %}

projects/templates/projects/multiple-projects.html
{% extends 'main.html' %}

{% block content %}
<h1>
    Projects
</h1>

<ul>
    {% for project in projects %}
    <li>
        <a href="{% url 'project' project.id %}">{{project.title}} </a>- {{project.vote_total}} ({{project.vote_ratio}}%)
    </li>
    {% endfor %}
</ul>

{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}
<h1>
    {{project.title}} 
    <span>{{project.votes_total|default:"0"}} votes </span>
    (<span style="color: green">{{project.votes_ratio|default:"-"}}%</span>)

</h1>
<p>{{project.description}}</p>

<h4>Reviews</h4>
{% for review in project.review_set.all%}
    {{review.value}} - {{review.body}}
    <hr>
{% endfor %}

{% endblock content %}