accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from devsearch import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='projects/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import include, path
from . import views

app_name = "profiles"

skill_urlpatterns = [
    path("create/", views.create_skill, name="create-skill"),
    path("edit/<uuid:pk>", views.edit_skill, name="edit-skill"),
    path("delete/<uuid:pk>", views.delete_skill, name="delete-skill"),
]

personal_urlpatterns = [
    path('', views.personal_profile, name='personal'),
    path('skills/', include(skill_urlpatterns)),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<uuid:pk>', views.message, name='message'),
    path('inbox/create/', views.create_message, name='create-message'),
]

urlpatterns = [
    path('', views.profiles, name='list'),
    path('<uuid:pk>/', views.profile, name='get'),
    path('personal/', include(personal_urlpatterns)),
    
]

projects/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings
app_name = "projects"
urlpatterns = [
    path('', views.projects, name='list'),
    path('<uuid:pk>', views.project, name='get'),
    path('create/', views.create_project, name='create'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit'),
    path('<uuid:pk>/delete/', views.delete_project, name='delete'),
]

templates/delete.html
{% extends 'main.html' %}
{% block content %}
<body>
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <form class="form" method="POST">
                    {% csrf_token %}
                    <p> Are you sure you want to delete "{{object}}"?</p>
                    <a href="{{request.GET.next}}">Cancel</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!--Fontawasome -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert--{{message.tags}}">
                <p class="alert__message">{{message}}</p>
                <button class="alert__close" onclick="closeMessage()">x</button>
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}


</body>
<script src="https://unpkg.com/@highlightjs/cdn-assets@10.7.1/highlight.min.js"></script>
<script src="{% static 'js/pagination-search-query.js'%}"></script>
<script src="{% static 'js/close-message.js'%}"></script>
</html>

templates/navbar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
      <a href="{% url 'projects:list' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'profiles:list' %}"> Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:list' %}" >Projects</a></li>          
          
          {% if request.user.is_authenticated %}
            <li class="header__menuItem"><a href="{% url 'profiles:inbox' %}" >Inbox</a></li> 
            <li class="header__menuItem"><a href="{% url 'profiles:personal' %}">Account</a></li>
            <li class="header__menuItem"><a href="{% url 'accounts:logout' %}" class="btn btn--sub">Logout</a></li>
          {% else %}
            <li class="header__menuItem"><a href="{% url 'accounts:login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
</header>

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination" data-testid="pagination">
  <ul class="container">
    {% if queryset.has_previous %}
      <li><a href="?page={{queryset.previous_page_number}}" class="btn page-link" data-page="{{queryset.previous_page_number}}">&#10094; Prev</a></li>
    
    {% else %}
      <li><a href="#" class="btn page-link btn--disabled">&#10094; Prev</a></li>
    {% endif %}

    
    {% for page in paginator.page_range %}
    {% if page == queryset.number %}
      <li data-testid="page-number"><a href="?page={{page}}" class="btn page-link btn--sub" data-page="{{page}}">{{page}}</a></li>
    {% elif page > queryset.number|add:'-3' and page < queryset.number|add:'3' %}
      <li data-testid="page-number"><a href="?page={{page}}" class="btn page-link" data-page="{{page}}">{{page}}</a></li>
    {% endif %}
    {% endfor %}

    {% if queryset.has_next %}
    <li><a href="?page={{queryset.next_page_number}}" class="btn page-link" data-page="{{queryset.next_page_number}}">Next &#10095;</a></li>
    {% else %}
    <li><a href="#" class="btn btn--disabled">Next &#10095;</a></li>
    {% endif %}
  </ul>
</div>
{% endif %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="uikit/styles/uikit.css" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="styles/app.css" />

    <title>DevSearch - Connect with Developers!</title>
  </head>

  <body>
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="images/icon.svg" alt="icon" />
          </a>
          <h3>Account SignUp</h3>
          <p>Create a new developer account</p>
        </div>

        <form action="#" class="form auth__form">
          <!-- Input:Text -->
          <div class="form__field">
            <label for="formInput#text">Full Name: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="text"
              placeholder="e.g. Dennis Ivanov"
            />
          </div>

          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#email">Email Address: </label>
            <input
              class="input input--email"
              id="formInput#email"
              type="email"
              name="email"
              placeholder="e.g. user@domain.com"
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#confirm-password">Confirm Password: </label>
            <input
              class="input input--password"
              id="formInput#confirm-passowrd"
              type="password"
              name="confirm-password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="login.html">Log In</a>
        </div>
      </div>
    </div>
  </body>
</html>